// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// call_glm_solver
Rcpp::List call_glm_solver(Rcpp::NumericMatrix& X_mat, Rcpp::NumericVector& y_vec, Rcpp::NumericVector& obs_weights, Rcpp::NumericVector& pen_factors, Rcpp::NumericVector& kappa_vec, Rcpp::NumericVector& lambda_vec, Rcpp::NumericVector& delta_val, Rcpp::NumericVector& tau_val, Rcpp::NumericVector& tol_val, Rcpp::NumericVector& cd_maxit_val, Rcpp::NumericVector& standardize_val, Rcpp::CharacterVector& family_val, Rcpp::CharacterVector& method_val);
RcppExport SEXP _glmtlp_call_glm_solver(SEXP X_matSEXP, SEXP y_vecSEXP, SEXP obs_weightsSEXP, SEXP pen_factorsSEXP, SEXP kappa_vecSEXP, SEXP lambda_vecSEXP, SEXP delta_valSEXP, SEXP tau_valSEXP, SEXP tol_valSEXP, SEXP cd_maxit_valSEXP, SEXP standardize_valSEXP, SEXP family_valSEXP, SEXP method_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type X_mat(X_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type obs_weights(obs_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type pen_factors(pen_factorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type kappa_vec(kappa_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type lambda_vec(lambda_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type delta_val(delta_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type tau_val(tau_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type tol_val(tol_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type cd_maxit_val(cd_maxit_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type standardize_val(standardize_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type family_val(family_valSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type method_val(method_valSEXP);
    rcpp_result_gen = Rcpp::wrap(call_glm_solver(X_mat, y_vec, obs_weights, pen_factors, kappa_vec, lambda_vec, delta_val, tau_val, tol_val, cd_maxit_val, standardize_val, family_val, method_val));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmtlp_call_glm_solver", (DL_FUNC) &_glmtlp_call_glm_solver, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmtlp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
