# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call_glm_solver <- function(X_mat, y_vec, obs_weights, pen_factors, kappa_vec, lambda_vec, delta_val, tau_val, tol_val, cd_maxit_val, standardize_val, family_val, method_val) {
    .Call(`_glmtlp_call_glm_solver`, X_mat, y_vec, obs_weights, pen_factors, kappa_vec, lambda_vec, delta_val, tau_val, tol_val, cd_maxit_val, standardize_val, family_val, method_val)
}

